concurrency: ci-${{ github.ref }}

on:
  push:
  workflow_call:
    inputs:
      token:
        type: string
      repo:
        type: string
      branch:
        type: string

name: UpdateReadme
jobs:
  web-deploy:
    name: Ubuntu VM
    runs-on: ubuntu-latest
    steps:
    - name: Getting latest Code
      uses: actions/checkout@v2.3.2
      
    - name: wget
      uses: wei/wget@v1
      with:
        args: -O badges.md https://raw.githubusercontent.com/costateixeira/ig-badges/main/badges.md    
      
    - name: Replace text in badges file with current repo values
      run: |
        sed -i -e "s|__GH_OWNER__|${GITHUB_REPOSITORY_OWNER}|g" badges.md
        sed -i -e "s|__GH_BRANCH__|${GITHUB_REF##*/}|g"         badges.md
        sed -i -e "s|__GH_REPO__|${GITHUB_REPOSITORY##*/}|g"    badges.md
        ERRS=$(jq '.errs' qa.json)
        WARNINGS=$(jq '.warnings' output/qa.json)
        sed -i -e "s|__ERRS__|$ERRS|g" output/badges.md
        sed -i -e "s|__WARNINGS__|$WARNINGS|g" badges.md
        
    - name: replace include with content of badges
      run: |
        awk 'NR==FNR{new = new $0 ORS; next} /<!--\/badges-->/{f=0} !f{print} /<!--badges-->/{printf "%s",new; f=1}' badges.md README.md > README_NEW.md && mv README_NEW.md README.md
        cat README.md
    - run: ls

    - run: |
        rm badges.md
        
    - name: stage changed files
      run: git add ./README.md

    - name: Deploy candidate
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: ${{ github.ref_name }} # The branch the action should deploy to.
        folder: . # The folder the action should deploy.
        commit-message: Deploy branch
        target-folder: .
        clean: false 
