#env:
#  gh_owner: ${GITHUB_REPOSITORY_OWNER}
concurrency: ci-${{ github.ref }}

on: push
name: FTP Deploy
jobs:
  web-deploy:
    name: Ubuntu VM
    runs-on: ubuntu-latest
    steps:
    - name: Getting latest Code
      uses: actions/checkout@v2.3.2
    - name: Replace text
      run: |
        sed -i -e "s|__GH_OWNER__|${GITHUB_REPOSITORY_OWNER}|g" README_SRC.md
        sed -i -e "s|__GH_BRANCH__|${GITHUB_REF##*/}|g"         README_SRC.md
        sed -i -e "s|__GH_REPO__|${GITHUB_REPOSITORY##*/}|g"    README_SRC.md

#    - name: stage changed files
      run: cp README_SRC.md README.md

#    - name: stage changed files
#      run: git add ./text.txt

    - name: Deploy candidate
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
#        branch: ${GITHUB_REF##*/} # The branch the action should deploy to.
        branch: main # The branch the action should deploy to.
        folder: . # The folder the action should deploy.
        commit-message: Deploy branch
        target-folder: .
        clean: false 
