#env:
#  gh_owner: ${GITHUB_REPOSITORY_OWNER}
concurrency: ci-${{ github.ref }}

on:
  push:
  workflow_call:
    inputs:
      token:
        required: true
        type: string
      repo:
        required: true
        type: string
      branch:
        required: true
        type: string


name: UpdateReadme
jobs:
  web-deploy:
    name: Ubuntu VM
    runs-on: ubuntu-latest
    steps:
    - name: Getting latest Code
      uses: actions/checkout@v2.3.2
      
    - name: wget
      uses: wei/wget@v1
      with:
        args: -O README_SRC.md https://raw.githubusercontent.com/costateixeira/ig-badges/main/README_SRC.md    
      
    - name: Create readme
      run: cp README_SRC.md README3.md

    - name: Replace text
      run: |
        sed -i -e "s|__GH_OWNER__|${GITHUB_REPOSITORY_OWNER}|g" README.md
        sed -i -e "s|__GH_BRANCH__|${GITHUB_REF##*/}|g"         README.md
        sed -i -e "s|__GH_REPO__|${GITHUB_REPOSITORY##*/}|g"    README.md

    - run: ls
    - name: stage changed files
      run: git add ./README.md

    - name: Deploy candidate
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
#        branch: ${GITHUB_REF##*/} # The branch the action should deploy to.
        branch: main # The branch the action should deploy to.
        folder: . # The folder the action should deploy.
        commit-message: Deploy branch
        target-folder: .
        clean: false 

#${{ inputs.repo }}

    - name: Pushes test file
      uses: tech-thinker/push-to-repo@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.GIT_PAT_TOKEN }}
      with:
        user-name: "github-actions[bot]"
        user-email: github-actions[bot]@users.noreply.github.com
        source-directory: "output-dir"
        destination-github-username: "username"
        destination-repository-name: '${{ inputs.token }}/${{ inputs.repo }}'
        target-branch: '${{ inputs.branch }}'

